@startuml
'https://plantuml.com/state-diagram

state Running
state Blocked
state Paused
state PausedReboot
state PausedReset
state ShutDown
state ShutOff
state Crashed
state PMSuspended

ShutOff --> Running : Create
Running --> Paused : Suspend
Paused --> Paused : Suspend
Paused --> Running : Resume
Paused --> PausedReboot : Reboot
PausedReboot --> Running : Resume
Paused --> PausedReset : Reset
PausedReset --> Running : Resume
Paused --> ShutOff : Destroy
Running --> ShutOff : ShutDown
Running --> ShutOff : Destroy
Running --> Running : Reboot
Running --> Running : Reset

}
@enduml