@startuml
'https://plantuml.com/state-diagram

state Running
state Blocked
state Paused
state ShutDown
state ShutOff
state Crashed
state PMSuspended

ShutOff --> Running : Create
Running --> Paused : Suspend
Paused --> Running : Resume
Running --> ShutOff : ShutDown\n(soft)
Running --> ShutOff : Destroy\n(hard)
Running --> Running : Reboot\n(soft)
Running --> Running : Reset\n(hard)

}
@enduml